/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as JornadaDeHonraRouteImport } from './routes/jornada-de-honra'
import { Route as AppsreObrigadoRouteImport } from './routes/appsre-obrigado'
import { Route as AppsreRouteImport } from './routes/appsre'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaDeHonraRoute = JornadaDeHonraRouteImport.update({
  id: '/jornada-de-honra',
  path: '/jornada-de-honra',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsreObrigadoRoute = AppsreObrigadoRouteImport.update({
  id: '/appsre-obrigado',
  path: '/appsre-obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsreRoute = AppsreRouteImport.update({
  id: '/appsre',
  path: '/appsre',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/appsre': typeof AppsreRoute
  '/appsre-obrigado': typeof AppsreObrigadoRoute
  '/jornada-de-honra': typeof JornadaDeHonraRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/appsre': typeof AppsreRoute
  '/appsre-obrigado': typeof AppsreObrigadoRoute
  '/jornada-de-honra': typeof JornadaDeHonraRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/appsre': typeof AppsreRoute
  '/appsre-obrigado': typeof AppsreObrigadoRoute
  '/jornada-de-honra': typeof JornadaDeHonraRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/appsre'
    | '/appsre-obrigado'
    | '/jornada-de-honra'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/appsre'
    | '/appsre-obrigado'
    | '/jornada-de-honra'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/appsre'
    | '/appsre-obrigado'
    | '/jornada-de-honra'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AppsreRoute: typeof AppsreRoute
  AppsreObrigadoRoute: typeof AppsreObrigadoRoute
  JornadaDeHonraRoute: typeof JornadaDeHonraRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada-de-honra': {
      id: '/jornada-de-honra'
      path: '/jornada-de-honra'
      fullPath: '/jornada-de-honra'
      preLoaderRoute: typeof JornadaDeHonraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appsre-obrigado': {
      id: '/appsre-obrigado'
      path: '/appsre-obrigado'
      fullPath: '/appsre-obrigado'
      preLoaderRoute: typeof AppsreObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appsre': {
      id: '/appsre'
      path: '/appsre'
      fullPath: '/appsre'
      preLoaderRoute: typeof AppsreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AppsreRoute: AppsreRoute,
  AppsreObrigadoRoute: AppsreObrigadoRoute,
  JornadaDeHonraRoute: JornadaDeHonraRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
