/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JornadaDeHonraRouteImport } from './routes/jornada-de-honra'
import { Route as AppsreRouteImport } from './routes/appsre'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'

const JornadaDeHonraRoute = JornadaDeHonraRouteImport.update({
  id: '/jornada-de-honra',
  path: '/jornada-de-honra',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsreRoute = AppsreRouteImport.update({
  id: '/appsre',
  path: '/appsre',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/appsre': typeof AppsreRoute
  '/jornada-de-honra': typeof JornadaDeHonraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/appsre': typeof AppsreRoute
  '/jornada-de-honra': typeof JornadaDeHonraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/appsre': typeof AppsreRoute
  '/jornada-de-honra': typeof JornadaDeHonraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$slug' | '/appsre' | '/jornada-de-honra'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug' | '/appsre' | '/jornada-de-honra'
  id: '__root__' | '/' | '/$slug' | '/appsre' | '/jornada-de-honra'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AppsreRoute: typeof AppsreRoute
  JornadaDeHonraRoute: typeof JornadaDeHonraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jornada-de-honra': {
      id: '/jornada-de-honra'
      path: '/jornada-de-honra'
      fullPath: '/jornada-de-honra'
      preLoaderRoute: typeof JornadaDeHonraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appsre': {
      id: '/appsre'
      path: '/appsre'
      fullPath: '/appsre'
      preLoaderRoute: typeof AppsreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AppsreRoute: AppsreRoute,
  JornadaDeHonraRoute: JornadaDeHonraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
